name: mahasiswa_app
description: Aplikasi Mahasiswa Flutter (dengan dark mode, font kece, dan layout adaptif)

publish_to: 'none' # karena ini project lokal, tidak publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/